# Generated by Django 6.0.2 on 2026-02-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('required_skills', models.CharField(help_text='Comma separated (e.g., Python, SQL, React)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
