# Generated by Django 6.0.2 on 2026-02-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default=None, upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
